name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  github:
    name: GitHub
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3
          bundler-cache: true
      - name: Publish to GitHub
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          RUBYGEMS_HOST: https://rubygems.pkg.github.com/${{github.repository_owner}}
        run: bin/release
  rubygems:
    name: RubyGems
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3
          bundler-cache: true
      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_TOKEN}}"
        run: bin/release
  tag:
    name: Git Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3
          bundler-cache: true
      - name: Tag
        run: bin/tag
